### ISSUE TITLE
this is a new error with 2c

### ISSUE THREAD

**Issue by LooperzZ** [ewrfcas/CasMTR#1]
Traceback (most recent call last):
  File "/home/test/PyCharm/CasMTR-main/test_single_pair.py", line 116, in <module>
    main()
  File "/home/test/PyCharm/CasMTR-main/test_single_pair.py", line 58, in main
    matcher(batch)
  File "/home/test/anaconda3/envs/pytorch-gpu/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/test/PyCharm/CasMTR-main/src/model/cascade_model_stage4.py", line 195, in forward
    mask_c0=mask_2c0, mask_c1=mask_2c1, heatmap_c0=heatmap_2c0, level='2c', pre_level=['8c', '4c'])
  File "/home/test/PyCharm/CasMTR-main/src/model/functions/cascade_matching.py", line 120, in forward
    sim_matrix01 /= self.temperature
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Process finished with exit code 1

torch==1.10.1+cu113

**Comment by ewrfcas** [comment]
Hi, what's the input image size? Because of the hard code in CUDA, our released codes only support image size<=1344 for CasMTR-2c, which may differ from different GPU device types. You could try CasMTR-4c instead. Unfortunately, our GPU servers are being maintained now, so I have to update the CUDA codes later.

**Comment by ewrfcas** [comment]
We have updated CUDA codes for better allocation for high-resolution.
Please ```pip uninstall score_computation_package``` and then ```rm -r cuda_imp/score_cuda/score_computation_package.egg-info``` and ```rm -r cuda_imp/score_cuda/dist```. Then you could try to re-install by ```cd cuda_imp/score_cuda&&python setup.py install```.
